# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NGram-FuzzySearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NGram-FuzzySearch
  pod 'Charts'

  target 'NGram-FuzzySearchUITests' do
    # Pods for testing
  end

end
